// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AddProject(arg1:string):Promise<string>;

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Branches(arg1:string):Promise<main.BranchInfo>;

export function Checkout(arg1:string,arg2:string):Promise<string>;

export function CommitActivity(arg1:string,arg2:number):Promise<Array<main.DayCountView>>;

export function CommitAll(arg1:string,arg2:string):Promise<string>;

export function DeleteProject(arg1:string):Promise<string>;

export function DeleteTask(arg1:string,arg2:string):Promise<string>;

export function DiffFile(arg1:string,arg2:string):Promise<string>;

export function Fetch(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetProject(arg1:string):Promise<main.ProjectView>;

export function ListProjects():Promise<Array<main.ProjectView>>;

export function LoadRepo(arg1:string):Promise<main.RepoView>;

export function Log(arg1:string,arg2:number):Promise<Array<main.CommitView>>;

export function OpenEditor(arg1:string):Promise<string>;

export function OpenInBrowser(arg1:string):Promise<string>;

export function OpenTerminal(arg1:string):Promise<string>;

export function Pull(arg1:string):Promise<string>;

export function Push(arg1:string):Promise<string>;

export function RepoGraph():Promise<main.GraphView>;

export function RevealInExplorer(arg1:string):Promise<string>;

export function RunCommand(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanRepos():Promise<Array<main.RepoView>>;

export function SetTags(arg1:string,arg2:Array<string>):Promise<string>;

export function Stash(arg1:string):Promise<string>;

export function StashList(arg1:string):Promise<Array<string>>;

export function StashPop(arg1:string):Promise<string>;

export function ToggleTask(arg1:string,arg2:string):Promise<string>;

export function UpdateProject(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<string>;
