// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LoadRepo(arg1) {
  return window['go']['main']['App']['LoadRepo'](arg1);
}

export function OpenEditor(arg1) {
  return window['go']['main']['App']['OpenEditor'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanRepos() {
  return window['go']['main']['App']['ScanRepos']();
}
