// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {main} from '../models';

export function Fetch(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function LoadRepo(arg1:string):Promise<main.RepoView>;

export function OpenEditor(arg1:string):Promise<string>;

export function OpenTerminal(arg1:string):Promise<string>;

export function Pull(arg1:string):Promise<string>;

export function RunCommand(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanRepos():Promise<Array<main.RepoView>>;
