// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Branches(arg1) {
  return window['go']['main']['App']['Branches'](arg1);
}

export function Checkout(arg1, arg2) {
  return window['go']['main']['App']['Checkout'](arg1, arg2);
}

export function CommitAll(arg1, arg2) {
  return window['go']['main']['App']['CommitAll'](arg1, arg2);
}

export function DiffFile(arg1, arg2) {
  return window['go']['main']['App']['DiffFile'](arg1, arg2);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function LoadRepo(arg1) {
  return window['go']['main']['App']['LoadRepo'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function OpenEditor(arg1) {
  return window['go']['main']['App']['OpenEditor'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['main']['App']['Push'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanRepos() {
  return window['go']['main']['App']['ScanRepos']();
}

export function Stash(arg1) {
  return window['go']['main']['App']['Stash'](arg1);
}

export function StashList(arg1) {
  return window['go']['main']['App']['StashList'](arg1);
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}
