// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function AIAvailable():Promise<boolean>;

export function AICheck(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function AddEdge(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function AddProject(arg1:string):Promise<string>;

export function AddTask(arg1:string,arg2:string,arg3:string):Promise<string>;

export function Agenda():Promise<Array<main.AgendaItem>>;

export function AgentAsk(arg1:string,arg2:string):Promise<string>;

export function AgentAskFleet(arg1:string):Promise<string>;

export function AgentAvailable():Promise<boolean>;

export function AgentConsent():Promise<boolean>;

export function ApproveAction(arg1:string,arg2:boolean):Promise<void>;

export function AskAI(arg1:string):Promise<string>;

export function AuthStart():Promise<string>;

export function AuthStatus():Promise<main.AuthStatusView>;

export function Branches(arg1:string):Promise<main.BranchInfo>;

export function CancelAI():Promise<void>;

export function CancelAgent():Promise<void>;

export function CancelAuth():Promise<void>;

export function Checkout(arg1:string,arg2:string):Promise<string>;

export function CloneUncloned(arg1:string,arg2:string):Promise<string>;

export function CommitActivity(arg1:string,arg2:number):Promise<Array<main.DayCountView>>;

export function CommitAll(arg1:string,arg2:string):Promise<string>;

export function CommitAmend(arg1:string,arg2:string):Promise<string>;

export function CommitStaged(arg1:string,arg2:string):Promise<string>;

export function CreateBranch(arg1:string,arg2:string):Promise<string>;

export function DeleteAccount():Promise<string>;

export function DeleteBranch(arg1:string,arg2:string):Promise<string>;

export function DeleteProject(arg1:string):Promise<string>;

export function DeleteTask(arg1:string,arg2:string):Promise<string>;

export function DetectEditors():Promise<Array<main.EditorOption>>;

export function DiffAll(arg1:string):Promise<string>;

export function DiffFile(arg1:string,arg2:string):Promise<string>;

export function DirExists(arg1:string):Promise<boolean>;

export function EditTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExportData():Promise<string>;

export function Fetch(arg1:string):Promise<string>;

export function GetConfig():Promise<config.Config>;

export function GetProject(arg1:string):Promise<main.ProjectView>;

export function GitHubInfo(arg1:string):Promise<main.GitHubView>;

export function GitHubSignals():Promise<Array<main.RepoGHSignal>>;

export function GitHubURL(arg1:string):Promise<string>;

export function GiveAgentConsent():Promise<string>;

export function LastCommitMessage(arg1:string):Promise<string>;

export function ListEdges():Promise<Array<main.EdgeView>>;

export function ListProjects():Promise<Array<main.ProjectView>>;

export function LoadRepo(arg1:string):Promise<main.RepoView>;

export function Log(arg1:string,arg2:number):Promise<Array<main.CommitView>>;

export function MergeUpstream(arg1:string):Promise<string>;

export function NotionAvailable():Promise<boolean>;

export function NotionComplete(arg1:string,arg2:string):Promise<string>;

export function NotionDatabases(arg1:string):Promise<main.NotionDBList>;

export function NotionTasks():Promise<main.NotionResult>;

export function OpenEditor(arg1:string):Promise<string>;

export function OpenEditorAt(arg1:string,arg2:string):Promise<string>;

export function OpenInBrowser(arg1:string):Promise<string>;

export function OpenTerminal(arg1:string):Promise<string>;

export function OpenURL(arg1:string):Promise<string>;

export function Pull(arg1:string):Promise<string>;

export function Push(arg1:string):Promise<string>;

export function ReadRepoFile(arg1:string,arg2:string):Promise<string>;

export function RebaseUpstream(arg1:string):Promise<string>;

export function RemoveEdge(arg1:string):Promise<string>;

export function RenameProject(arg1:string,arg2:string):Promise<string>;

export function ReorderTasks(arg1:string,arg2:Array<string>):Promise<string>;

export function RepoDiff(arg1:string):Promise<string>;

export function RepoFiles(arg1:string,arg2:string):Promise<string>;

export function RepoGraph():Promise<main.GraphView>;

export function RepoGrep(arg1:string,arg2:string):Promise<string>;

export function RepoSymbols(arg1:string):Promise<main.SymbolsView>;

export function RevealInExplorer(arg1:string):Promise<string>;

export function RunCommand(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:config.Config):Promise<string>;

export function ScanRepos():Promise<Array<main.RepoView>>;

export function SearchAll(arg1:string):Promise<Array<main.SearchHit>>;

export function SearchFiles(arg1:string):Promise<Array<main.FileHit>>;

export function SetTags(arg1:string,arg2:Array<string>):Promise<string>;

export function SetTaskStatus(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SignOut():Promise<string>;

export function StageFile(arg1:string,arg2:string):Promise<string>;

export function StagedDiff(arg1:string):Promise<string>;

export function Stash(arg1:string):Promise<string>;

export function StashApply(arg1:string,arg2:number):Promise<string>;

export function StashDrop(arg1:string,arg2:number):Promise<string>;

export function StashList(arg1:string):Promise<Array<string>>;

export function StashPop(arg1:string):Promise<string>;

export function StatusFiles(arg1:string):Promise<Array<main.StatusFilesView>>;

export function SyncNow():Promise<string>;

export function SyncState():Promise<main.SyncStateView>;

export function SyncedUncloned():Promise<Array<main.UnclonedView>>;

export function ToggleTask(arg1:string,arg2:string):Promise<string>;

export function UnstageFile(arg1:string,arg2:string):Promise<string>;

export function UpdateProject(arg1:string,arg2:string,arg3:number,arg4:string,arg5:string):Promise<string>;
