// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIAvailable() {
  return window['go']['main']['App']['AIAvailable']();
}

export function AICheck(arg1, arg2, arg3) {
  return window['go']['main']['App']['AICheck'](arg1, arg2, arg3);
}

export function AddEdge(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddEdge'](arg1, arg2, arg3, arg4);
}

export function AddProject(arg1) {
  return window['go']['main']['App']['AddProject'](arg1);
}

export function AddTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTask'](arg1, arg2, arg3);
}

export function Agenda() {
  return window['go']['main']['App']['Agenda']();
}

export function AskAI(arg1) {
  return window['go']['main']['App']['AskAI'](arg1);
}

export function AuthStart() {
  return window['go']['main']['App']['AuthStart']();
}

export function AuthStatus() {
  return window['go']['main']['App']['AuthStatus']();
}

export function Branches(arg1) {
  return window['go']['main']['App']['Branches'](arg1);
}

export function CancelAI() {
  return window['go']['main']['App']['CancelAI']();
}

export function Checkout(arg1, arg2) {
  return window['go']['main']['App']['Checkout'](arg1, arg2);
}

export function CommitActivity(arg1, arg2) {
  return window['go']['main']['App']['CommitActivity'](arg1, arg2);
}

export function CommitAll(arg1, arg2) {
  return window['go']['main']['App']['CommitAll'](arg1, arg2);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1, arg2) {
  return window['go']['main']['App']['DeleteTask'](arg1, arg2);
}

export function DiffFile(arg1, arg2) {
  return window['go']['main']['App']['DiffFile'](arg1, arg2);
}

export function Fetch(arg1) {
  return window['go']['main']['App']['Fetch'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GitHubInfo(arg1) {
  return window['go']['main']['App']['GitHubInfo'](arg1);
}

export function GitHubURL(arg1) {
  return window['go']['main']['App']['GitHubURL'](arg1);
}

export function ListEdges() {
  return window['go']['main']['App']['ListEdges']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function LoadRepo(arg1) {
  return window['go']['main']['App']['LoadRepo'](arg1);
}

export function Log(arg1, arg2) {
  return window['go']['main']['App']['Log'](arg1, arg2);
}

export function NotionAvailable() {
  return window['go']['main']['App']['NotionAvailable']();
}

export function NotionComplete(arg1, arg2) {
  return window['go']['main']['App']['NotionComplete'](arg1, arg2);
}

export function NotionDatabases(arg1) {
  return window['go']['main']['App']['NotionDatabases'](arg1);
}

export function NotionTasks() {
  return window['go']['main']['App']['NotionTasks']();
}

export function OpenEditor(arg1) {
  return window['go']['main']['App']['OpenEditor'](arg1);
}

export function OpenEditorAt(arg1, arg2) {
  return window['go']['main']['App']['OpenEditorAt'](arg1, arg2);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function Pull(arg1) {
  return window['go']['main']['App']['Pull'](arg1);
}

export function Push(arg1) {
  return window['go']['main']['App']['Push'](arg1);
}

export function ReadRepoFile(arg1, arg2) {
  return window['go']['main']['App']['ReadRepoFile'](arg1, arg2);
}

export function RemoveEdge(arg1) {
  return window['go']['main']['App']['RemoveEdge'](arg1);
}

export function ReorderTasks(arg1, arg2) {
  return window['go']['main']['App']['ReorderTasks'](arg1, arg2);
}

export function RepoDiff(arg1) {
  return window['go']['main']['App']['RepoDiff'](arg1);
}

export function RepoFiles(arg1, arg2) {
  return window['go']['main']['App']['RepoFiles'](arg1, arg2);
}

export function RepoGraph() {
  return window['go']['main']['App']['RepoGraph']();
}

export function RepoGrep(arg1, arg2) {
  return window['go']['main']['App']['RepoGrep'](arg1, arg2);
}

export function RepoSymbols(arg1) {
  return window['go']['main']['App']['RepoSymbols'](arg1);
}

export function RevealInExplorer(arg1) {
  return window['go']['main']['App']['RevealInExplorer'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanRepos() {
  return window['go']['main']['App']['ScanRepos']();
}

export function SearchAll(arg1) {
  return window['go']['main']['App']['SearchAll'](arg1);
}

export function SetTags(arg1, arg2) {
  return window['go']['main']['App']['SetTags'](arg1, arg2);
}

export function SetTaskStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTaskStatus'](arg1, arg2, arg3);
}

export function SignOut() {
  return window['go']['main']['App']['SignOut']();
}

export function StagedDiff(arg1) {
  return window['go']['main']['App']['StagedDiff'](arg1);
}

export function Stash(arg1) {
  return window['go']['main']['App']['Stash'](arg1);
}

export function StashList(arg1) {
  return window['go']['main']['App']['StashList'](arg1);
}

export function StashPop(arg1) {
  return window['go']['main']['App']['StashPop'](arg1);
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function SyncState() {
  return window['go']['main']['App']['SyncState']();
}

export function ToggleTask(arg1, arg2) {
  return window['go']['main']['App']['ToggleTask'](arg1, arg2);
}

export function UpdateProject(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2, arg3, arg4, arg5);
}
